Feat/bac 12 transcription service
workshopapps/customersupport.web pull request #312
Opened 2022-11-25 06:51 UTC by Tamunonengiyeofori

I have created the transcripts.py file and updated it with endpoints to retrieve a transcript by ID get all transcripts

2022-11-25 21:07 UTC, ColeDrain commented on .gitignore
>  # Local Netlify folder
where is this coming from, kindly delete ?

2022-11-25 21:11 UTC, ColeDrain commented on backend/app/routers/transcript.py
> +#ENDPOINT TO GET ALL TRANSCRIPTS AS A LIST
This brings integrity issues, you are getting transcripts of everyone, I don't think this is something that should happen.
Transcripts are personal to companies/users.

2022-11-25 21:12 UTC, ColeDrain requested changes
Good one, but some issues that would break our app.

- requirements.txt file is outside of backend/app directory and contains unneeded 
dependencies, please resolve

- Delete routes/view_transcripts.py instead of commenting out

- Please fix your directory structure, it doesn't follow dev or main, some folders are outside backend/app (our working directory)

- Why do we have trascript.py again, put the functionality into transcribe.py

- .gitignore file outside of working directory

- And other comments I made

2022-11-25 21:13 UTC, Tamunonengiyeofori commented on backend/app/routers/transcript.py
> +#ENDPOINT TO GET ALL TRANSCRIPTS AS A LIST
I was told by the frontend dev to get the transcripts of everyone

2022-11-26 13:54 UTC, Tamunonengiyeofori commented
I have resolved the merge conflicts

2022-11-26 14:39 UTC, ColeDrain commented on backend/app/main.py
> +=======
Bro please fix this (=====)

2022-11-26 14:45 UTC, ColeDrain requested changes

2022-11-26 14:45 UTC, ColeDrain commented on backend/app/main.py
> +
please also remove this line please, for the sake of clarity

2022-11-26 14:45 UTC, ColeDrain commented on backend/app/routers/transcribe.py
> +def transcribe_file(filename):
did you sync with @DavidIkechi 
we are using Assembly AI, so Banana dev code should be removed

2022-11-26 14:45 UTC, ColeDrain commented on backend/app/routers/transcribe.py
> +@transcript_router.get("/{job_id}", description="Retrieving transcript by audio ID")
please protect this endpoint
only logged in user should have access to this

2022-11-26 14:45 UTC, ColeDrain commented on backend/app/routers/transcribe.py
> +@transcript_router.get("/view_transcripts", response_model=List[schema.Audio], description="Retrieve all Transcripts")
same as above here

2022-11-26 15:29 UTC, Tamunonengiyeofori commented on backend/app/routers/transcribe.py
> +def transcribe_file(filename):
I have spoken with him and corrected the code for that.

2022-11-26 15:47 UTC, DavidIkechi commented
please I need to test your code to ensure it's working before it can be merged

2022-11-26 15:48 UTC, DavidIkechi commented
If you are ready, we can go on a call, to avoid any break on the server.

2022-11-26 15:53 UTC, Tamunonengiyeofori commented on backend/app/routers/transcribe.py
> +@transcript_router.get("/{job_id}", description="Retrieving transcript by audio ID")
I have resolved this issue

2022-11-26 19:27 UTC, DavidIkechi approved these changes
Weldone bro, this looks better

2022-11-26 20:13 UTC, ColeDrain approved these changes

2022-11-26 20:14 UTC, merged