made changes to the free trial end point
workshopapps/customersupport.web pull request #324
Opened 2022-11-25 11:41 UTC by KlyntonREP

called the transcribe function instead of writing it afresh

2022-11-25 13:47 UTC, ColeDrain requested changes
- Please delete freetrial.py instead of commenting it out

- And I see you check if a file is uploaded (line 230) after you copy it (line 226). This will break app if no file is uploaded.

Key points:
Check if file is not uploaded at beginning of the function
Delete freetrial.py

2022-11-25 13:49 UTC, ColeDrain commented on backend/app/main.py
> +import shutil
does this dependency need to be installed ?

2022-11-25 13:50 UTC, ColeDrain commented on backend/app/main.py
> +    if not file:
You are checking if file is empty after copying its content

2022-11-25 13:51 UTC, KlyntonREP commented
No boss

shutil doesn't need to be installed,  it comes wigh python

On Fri, Nov 25, 2022, 2:49 PM Ugochukwu Onyebuchi ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In backend/app/main.py
> <https://github.com/workshopapps/customersupport.web/pull/324#discussion_r1032472080>
> :
>
> > @@ -22,6 +22,9 @@
>  import fastapi as _fastapi
>  from auth import get_current_user
>
> +import shutil
>
> does this dependency need to be installed ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/workshopapps/customersupport.web/pull/324#pullrequestreview-1194465451>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQNWTQKKU7QWEQDGIDTYXVLWKC7WRANCNFSM6AAAAAASLHQL6E>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-25 13:52 UTC, KlyntonREP commented
Ok boss, i make changes and make a new PR

On Fri, Nov 25, 2022, 2:50 PM Ugochukwu Onyebuchi ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In backend/app/main.py
> <https://github.com/workshopapps/customersupport.web/pull/324#discussion_r1032472779>
> :
>
> > @@ -216,6 +219,24 @@ async def email_verification(request: Request, token: str, db: Session = Depends
>  def update_user(user: schema.user_update, user_id: int, db:Session=_fastapi.Depends(get_db)):
>       return crud.update_user(db=db, user=user, user_id=user_id)
>
> ***@***.***("/tryForFree")
> +async def free_trial(file: UploadFile = File(...)):
> +    ####### saving the audio file
> +    with open(f'{file.filename}', "wb") as buffer:
> +        shutil.copyfileobj(file.file, buffer)
> +    fileSize = 5242880
> +    getSize = os.path.getsize(file.filename)
> +    ###### transcribing the file
> +    if not file:
>
> You are checking if file is empty after copying its content
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/workshopapps/customersupport.web/pull/324#pullrequestreview-1194466475>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQNWTQIYGFOOV5W3LR6JXQDWKC7ZVANCNFSM6AAAAAASLHQL6E>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-26 15:30 UTC, DavidIkechi approved these changes
weldone bro

2022-11-26 15:33 UTC, KlyntonREP commented
Thanks boss

On Sat, Nov 26, 2022, 4:30 PM David Akwuru ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> weldone bro
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/workshopapps/customersupport.web/pull/324#pullrequestreview-1194884691>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQNWTQNQIO2QYZNP4ZEPFMTWKIUJZANCNFSM6AAAAAASLHQL6E>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-26 15:47 UTC, ColeDrain requested changes

2022-11-26 15:47 UTC, ColeDrain commented on backend/app/main.py
> +@app.get("/new_analysis/{id}", response_model=schema.Analysis, tags=['analysis'])
Great job, almost there bro, please remove this line

2022-11-26 16:09 UTC, KlyntonREP commented on backend/app/main.py
> +@app.get("/new_analysis/{id}", response_model=schema.Analysis, tags=['analysis'])
Thanks Boss, i've removed it

2022-11-26 16:47 UTC, ColeDrain approved these changes
Great job, all issues resolved

2022-11-26 16:48 UTC, merged